# Font
font_family firacode
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0
font_features FiraCode-Light +zero -liga -calt -clig
font_features FiraCode-Regular +zero -liga -calt -clig
font_features FiraCode-Retina +zero -liga -calt -clig
font_features FiraCode-Medium +zero -liga -calt -clig
font_features FiraCode-SemiBold +zero -liga -calt -clig
font_features FiraCode-Bold +zero -liga -calt -clig

# Color Scheme (based on Gogh's ayu-dark https://github.com/Gogh-Co/Gogh)
color0 #0A0E14
color1 #FF3333
color2 #C2D94C
color3 #FF8F40
color4 #59C2FF
color5 #FFEE99
color6 #95E6CB
color7 #B3B1AD

color8 #4D5566
color9 #FF3333
color10 #C2D94C
color11 #FF8F40
color12 #59C2FF
color13 #FFEE99
color14 #95E6CB
color15 #B3B1AD

background #0A0E14
foreground #B3B1AD

cursor #FFEE99

# Tab
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
tab_bar_min_tabs 2

active_tab_foreground   #000
active_tab_background   #ccc
active_tab_font_style   bold-italic
inactive_tab_foreground #222
inactive_tab_background #777
inactive_tab_font_style normal
